//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SmartMogila
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кладбище.
    /// </summary>
    //  *** Start programmer edit section *** (Кладбище CustomAttributes)

    //  *** End programmer edit section *** (Кладбище CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КладбищеE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Площадь as \'Площадь\'",
            "ФиоРуководителя as \'Фио руководителя\'"})]
    [View("КладбищеL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Площадь as \'Площадь\'",
            "ФиоРуководителя as \'Фио руководителя\'"})]
    public class Кладбище : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        private double fПлощадь;
        
        private string fФиоРуководителя;
        
        //  *** Start programmer edit section *** (Кладбище CustomMembers)

        //  *** End programmer edit section *** (Кладбище CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Кладбище.Название CustomAttributes)

        //  *** End programmer edit section *** (Кладбище.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Кладбище.Название Get start)

                //  *** End programmer edit section *** (Кладбище.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Кладбище.Название Get end)

                //  *** End programmer edit section *** (Кладбище.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Кладбище.Название Set start)

                //  *** End programmer edit section *** (Кладбище.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Кладбище.Название Set end)

                //  *** End programmer edit section *** (Кладбище.Название Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Кладбище.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Кладбище.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Кладбище.Адрес Get start)

                //  *** End programmer edit section *** (Кладбище.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Кладбище.Адрес Get end)

                //  *** End programmer edit section *** (Кладбище.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Кладбище.Адрес Set start)

                //  *** End programmer edit section *** (Кладбище.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Кладбище.Адрес Set end)

                //  *** End programmer edit section *** (Кладбище.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        //  *** Start programmer edit section *** (Кладбище.Площадь CustomAttributes)

        //  *** End programmer edit section *** (Кладбище.Площадь CustomAttributes)
        public virtual double Площадь
        {
            get
            {
                //  *** Start programmer edit section *** (Кладбище.Площадь Get start)

                //  *** End programmer edit section *** (Кладбище.Площадь Get start)
                double result = this.fПлощадь;
                //  *** Start programmer edit section *** (Кладбище.Площадь Get end)

                //  *** End programmer edit section *** (Кладбище.Площадь Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Кладбище.Площадь Set start)

                //  *** End programmer edit section *** (Кладбище.Площадь Set start)
                this.fПлощадь = value;
                //  *** Start programmer edit section *** (Кладбище.Площадь Set end)

                //  *** End programmer edit section *** (Кладбище.Площадь Set end)
            }
        }
        
        /// <summary>
        /// ФиоРуководителя.
        /// </summary>
        //  *** Start programmer edit section *** (Кладбище.ФиоРуководителя CustomAttributes)

        //  *** End programmer edit section *** (Кладбище.ФиоРуководителя CustomAttributes)
        [StrLen(255)]
        public virtual string ФиоРуководителя
        {
            get
            {
                //  *** Start programmer edit section *** (Кладбище.ФиоРуководителя Get start)

                //  *** End programmer edit section *** (Кладбище.ФиоРуководителя Get start)
                string result = this.fФиоРуководителя;
                //  *** Start programmer edit section *** (Кладбище.ФиоРуководителя Get end)

                //  *** End programmer edit section *** (Кладбище.ФиоРуководителя Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Кладбище.ФиоРуководителя Set start)

                //  *** End programmer edit section *** (Кладбище.ФиоРуководителя Set start)
                this.fФиоРуководителя = value;
                //  *** Start programmer edit section *** (Кладбище.ФиоРуководителя Set end)

                //  *** End programmer edit section *** (Кладбище.ФиоРуководителя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КладбищеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КладбищеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КладбищеE", typeof(IIS.SmartMogila.Кладбище));
                }
            }
            
            /// <summary>
            /// "КладбищеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КладбищеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КладбищеL", typeof(IIS.SmartMogila.Кладбище));
                }
            }
        }
    }
}
