//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SmartMogila
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние надгробия.
    /// </summary>
    //  *** Start programmer edit section *** (СостояниеНадгробия CustomAttributes)

    //  *** End programmer edit section *** (СостояниеНадгробия CustomAttributes)
    public enum СостояниеНадгробия
    {
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (СостояниеНадгробия.Отсутствует CustomAttributes)

        //  *** End programmer edit section *** (СостояниеНадгробия.Отсутствует CustomAttributes)
        Отсутствует,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (СостояниеНадгробия.Плохое CustomAttributes)

        //  *** End programmer edit section *** (СостояниеНадгробия.Плохое CustomAttributes)
        Плохое,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (СостояниеНадгробия.Хорошее CustomAttributes)

        //  *** End programmer edit section *** (СостояниеНадгробия.Хорошее CustomAttributes)
        Хорошее,
    }
}
